plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jarvis.ligarpcvoz'
    compileSdk 35

    defaultConfig {
        applicationId "com.jarvis.ligarpcvoz"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.13.1'
}
